
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: RunTest1
  displayName: 'Run Tests'
  pool: Default
  strategy:
    parallel: 2
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '3.x'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/MsTestUnitTestProject/MsTestUnitTestProject.csproj'
      feedsToUse: 'select'
    displayName: '.NET Core (Restore)'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/MsTestUnitTestProject/MsTestUnitTestProject.csproj'
      arguments: '--framework netcoreapp3.0 --configuration Release --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: false
    displayName: '.NET Core (Publish)'
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '**/MsTestSampleTests.dll'
      searchFolder: '$(Build.ArtifactStagingDirectory)'
      otherConsoleOptions: '/framework:".NETCoreApp,Version=v3.0"'
      batchingBasedOnAgentsOption: 'customBatchSize'
      runSettingsFile: 'sample.runsettings'
      failOnMinTestsNotRun: 'true'
      minimumExpectedTests: '5'