
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: RunTest1
  displayName: 'Run Tests'
  pool:
    vmImage: 'windows-latest'
  strategy:
    parallel: 2
  steps:
  - task: VisualStudioTestPlatformInstaller@1
    displayName: 'Visual Studio Test Platform Installer'
    inputs:
      versionSelector: 'latestPreRelease'
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: '**/*UnitTestProject*.dll'
      searchFolder: '$(System.DefaultWorkingDirectory)\UnitTestProject1\bin\Debug\'
      vsTestVersion: 'toolsInstaller'
      testFiltercriteria: 'Priority = 3 | FullyQualifiedName ~ TestRunParameter | FullyQualifiedName = NUnit.Tests1.TestClass.TestMethod'
      runSettingsFile: '$(System.DefaultWorkingDirectory)\UnitTestProject1\SampleTestsettings1.testsettings'
      overrideTestrunParameters: '-connectionString DataSource=tcp:ServerName.database.windows.net,1433;InitialCatalog=DatabaseName -param1 OverrideParam1Value'
      runInParallel: "true"
      codeCoverageEnabled: "true"
      testRunTitle: "VsTestV2WithCustomValuesTestWithTestSettings"
      platform: "Custom platform value"
      configuration: "Custom configuration value"
      publishRunAttachments: "true"
      pathtoCustomTestAdapters: "$(Build.SourcesDirectory)"